In [1]:
# blanket import modules
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np
import pprint

out_csv = "Output/multiple_year_data.csv"

In [2]:
# setting up paths for data
y2022_cs = "../Resources/World Happiness Report 2022.csv"
y2021_cs = "../Resources/2021.csv"
y2020_cs = "../Resources/2020.csv"
y2019_cs = "../Resources/2019.csv"
y2018_cs = "../Resources/2018.csv"
y2017_cs = "../Resources/2017.csv"
y2016_cs = "../Resources/2016.csv"
y2015_cs = "../Resources/2015.csv"

In [24]:
# making data pandas readable
y2022_df = pd.read_csv(y2022_cs)
y2021_df = pd.read_csv(y2021_cs)
y2020_df = pd.read_csv(y2020_cs)
y2019_df = pd.read_csv(y2019_cs)
y2018_df = pd.read_csv(y2018_cs)
y2017_df = pd.read_csv(y2017_cs)
y2016_df = pd.read_csv(y2016_cs)
y2015_df = pd.read_csv(y2015_cs)
y2016_df

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,Southern Asia,154,3.360,3.288,3.432,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,Sub-Saharan Africa,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,Middle East and Northern Africa,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,Sub-Saharan Africa,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

In [26]:
#grabbing data needed for merge
y2022_df_e = y2022_df.loc[: , ["RANK", "Country", "Happiness score"]]
y2021_df_e = y2021_df.loc[: , ["Country name", "Ladder score"]]
y2020_df_e = y2020_df.loc[: , ["Country name", "Ladder score"]]
y2019_df_e = y2019_df.loc[: , ["Overall rank", "Country or region", "Score"]]
y2018_df_e = y2018_df.loc[: , ["Overall rank", "Country or region", "Score"]]
y2017_df_e = y2017_df.loc[: , ["Happiness.Rank", "Country", "Happiness.Score"]]
y2016_df_e = y2016_df.loc[: , ["Happiness Rank", "Country", "Happiness Score"]]
y2015_df_e = y2015_df.loc[: , ["Happiness Rank", "Country", "Happiness Score"]]

In [27]:
y2021_df_e

    Country name  Ladder score
0        Finland         7.842
1        Denmark         7.620
2    Switzerland         7.571
3        Iceland         7.554
4    Netherlands         7.464
..           ...           ...
144      Lesotho         3.512
145     Botswana         3.467
146       Rwanda         3.415
147     Zimbabwe         3.145
148  Afghanistan         2.523

[149 rows x 2 columns]